spring.application.name=API Patitas Conectadas

# Configuración del puerto del servidor
#server.port=4000

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://d2vgllbe5dus73fmd83g-a.frankfurt-postgres.render.com/patitasconectadas
spring.datasource.username=usuario
spring.datasource.password=F36ZgqA5zvzOAxasUCOxNep3uzpeR5tz

# Configuración de Hibernate
# Eliminar esta linea spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

# Configuración del pool de conexiones
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# Configuración de carga de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads