--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: usuario; Type: TABLE; Schema: public; Owner: mouad
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    email character varying(50) NOT NULL,
    password character varying(250) NOT NULL,
    apellido character varying(50) NOT NULL
);


ALTER TABLE public.usuario OWNER TO mouad;

--
-- Name: Usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: mouad
--

CREATE SEQUENCE public."Usuario_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."Usuario_id_seq" OWNER TO mouad;

--
-- Name: Usuario_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: mouad
--

ALTER SEQUENCE public."Usuario_id_seq" OWNED BY public.usuario.id;


--
-- Name: chat; Type: TABLE; Schema: public; Owner: mouad
--

CREATE TABLE public.chat (
    id bigint NOT NULL,
    contenido character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    fecha_hora timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    visto boolean NOT NULL,
    emisor_id bigint NOT NULL,
    receptor_id bigint NOT NULL
);


ALTER TABLE public.chat OWNER TO mouad;

--
-- Name: chat_id_seq; Type: SEQUENCE; Schema: public; Owner: mouad
--

ALTER TABLE public.chat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comentario; Type: TABLE; Schema: public; Owner: mouad
--

CREATE TABLE public.comentario (
    id bigint NOT NULL,
    contenido character varying(1000),
    created_at timestamp(6) without time zone,
    fecha timestamp(6) without time zone NOT NULL,
    img character varying(255),
    updated_at timestamp(6) without time zone,
    usuario_id bigint NOT NULL,
    post_id bigint
);


ALTER TABLE public.comentario OWNER TO mouad;

--
-- Name: comentario_id_seq; Type: SEQUENCE; Schema: public; Owner: mouad
--

ALTER TABLE public.comentario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comentario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evento; Type: TABLE; Schema: public; Owner: mouad
--

CREATE TABLE public.evento (
    id bigint NOT NULL,
    descripcion character varying(250) NOT NULL,
    fecha date NOT NULL,
    nombre character varying(50) NOT NULL,
    ubicacion character varying(250) NOT NULL
);


ALTER TABLE public.evento OWNER TO mouad;

--
-- Name: evento_id_seq; Type: SEQUENCE; Schema: public; Owner: mouad
--

ALTER TABLE public.evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grupo; Type: TABLE; Schema: public; Owner: mouad
--

CREATE TABLE public.grupo (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    descripcion character varying(255) NOT NULL
);


ALTER TABLE public.grupo OWNER TO mouad;

--
-- Name: grupo_id_seq; Type: SEQUENCE; Schema: public; Owner: mouad
--

CREATE SEQUENCE public.grupo_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.grupo_id_seq OWNER TO mouad;

--
-- Name: grupo_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: mouad
--

ALTER SEQUENCE public.grupo_id_seq OWNED BY public.grupo.id;


--
-- Name: mascota; Type: TABLE; Schema: public; Owner: mouad
--

CREATE TABLE public.mascota (
    id bigint NOT NULL,
    genero character varying(10) NOT NULL,
    nombre character varying(50) NOT NULL,
    especie character varying(50) NOT NULL,
    usuario_id bigint NOT NULL,
    foto character varying(255),
    fecha_nacimiento date
);


ALTER TABLE public.mascota OWNER TO mouad;

--
-- Name: mascota_id_seq; Type: SEQUENCE; Schema: public; Owner: mouad
--

ALTER TABLE public.mascota ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mascota_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificaciones; Type: TABLE; Schema: public; Owner: mouad
--

CREATE TABLE public.notificaciones (
    id bigint NOT NULL,
    fecha timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.notificaciones OWNER TO mouad;

--
-- Name: notificaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: mouad
--

ALTER TABLE public.notificaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: perfil; Type: TABLE; Schema: public; Owner: mouad
--

CREATE TABLE public.perfil (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    descripcion character varying(255),
    fecha_nacimiento date,
    img character varying(255)
);


ALTER TABLE public.perfil OWNER TO mouad;

--
-- Name: perfil_id_seq; Type: SEQUENCE; Schema: public; Owner: mouad
--

CREATE SEQUENCE public.perfil_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.perfil_id_seq OWNER TO mouad;

--
-- Name: perfil_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: mouad
--

ALTER SEQUENCE public.perfil_id_seq OWNED BY public.perfil.id;


--
-- Name: post; Type: TABLE; Schema: public; Owner: mouad
--

CREATE TABLE public.post (
    id bigint NOT NULL,
    grupo_id bigint,
    creador_id bigint NOT NULL,
    contenido character varying(255),
    fecha timestamp(6) without time zone NOT NULL,
    img text,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.post OWNER TO mouad;

--
-- Name: post_id_seq; Type: SEQUENCE; Schema: public; Owner: mouad
--

CREATE SEQUENCE public.post_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.post_id_seq OWNER TO mouad;

--
-- Name: post_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: mouad
--

ALTER SEQUENCE public.post_id_seq OWNED BY public.post.id;


--
-- Name: seguido; Type: TABLE; Schema: public; Owner: mouad
--

CREATE TABLE public.seguido (
    id bigint NOT NULL,
    usuario_que_es_seguido_id bigint NOT NULL,
    usuario_que_sigue_id bigint NOT NULL
);


ALTER TABLE public.seguido OWNER TO mouad;

--
-- Name: seguido_id_seq; Type: SEQUENCE; Schema: public; Owner: mouad
--

ALTER TABLE public.seguido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seguido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_evento; Type: TABLE; Schema: public; Owner: mouad
--

CREATE TABLE public.usuario_evento (
    id bigint NOT NULL,
    rol character varying(255) NOT NULL,
    evento_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE public.usuario_evento OWNER TO mouad;

--
-- Name: usuario_evento_id_seq; Type: SEQUENCE; Schema: public; Owner: mouad
--

ALTER TABLE public.usuario_evento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_evento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_grupo; Type: TABLE; Schema: public; Owner: mouad
--

CREATE TABLE public.usuario_grupo (
    id bigint NOT NULL,
    grupo_id bigint,
    usuario_id bigint NOT NULL,
    rol character varying(255)
);


ALTER TABLE public.usuario_grupo OWNER TO mouad;

--
-- Name: usuario_grupo_id_seq; Type: SEQUENCE; Schema: public; Owner: mouad
--

CREATE SEQUENCE public.usuario_grupo_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.usuario_grupo_id_seq OWNER TO mouad;

--
-- Name: usuario_grupo_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: mouad
--

ALTER SEQUENCE public.usuario_grupo_id_seq OWNED BY public.usuario_grupo.id;


--
-- Name: usuario_post; Type: TABLE; Schema: public; Owner: mouad
--

CREATE TABLE public.usuario_post (
    id bigint NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    post_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE public.usuario_post OWNER TO mouad;

--
-- Name: usuario_post_id_seq; Type: SEQUENCE; Schema: public; Owner: mouad
--

ALTER TABLE public.usuario_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: valoracion; Type: TABLE; Schema: public; Owner: fernando
--

CREATE TABLE public.valoracion (
    id bigint NOT NULL,
    autor_id bigint NOT NULL,
    receptor_id bigint NOT NULL,
    puntuacion integer NOT NULL,
    contenido character varying(255) NOT NULL,
    fecha timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT valoracion_puntuacion_check CHECK (((puntuacion >= 1) AND (puntuacion <= 5)))
);


ALTER TABLE public.valoracion OWNER TO fernando;

--
-- Name: valoracion_id_seq; Type: SEQUENCE; Schema: public; Owner: fernando
--

CREATE SEQUENCE public.valoracion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.valoracion_id_seq OWNER TO fernando;

--
-- Name: valoracion_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fernando
--

ALTER SEQUENCE public.valoracion_id_seq OWNED BY public.valoracion.id;


--
-- Name: grupo id; Type: DEFAULT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.grupo ALTER COLUMN id SET DEFAULT nextval('public.grupo_id_seq'::regclass);


--
-- Name: perfil id; Type: DEFAULT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.perfil ALTER COLUMN id SET DEFAULT nextval('public.perfil_id_seq'::regclass);


--
-- Name: post id; Type: DEFAULT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.post ALTER COLUMN id SET DEFAULT nextval('public.post_id_seq'::regclass);


--
-- Name: usuario id; Type: DEFAULT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.usuario ALTER COLUMN id SET DEFAULT nextval('public."Usuario_id_seq"'::regclass);


--
-- Name: usuario_grupo id; Type: DEFAULT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.usuario_grupo ALTER COLUMN id SET DEFAULT nextval('public.usuario_grupo_id_seq'::regclass);


--
-- Name: valoracion id; Type: DEFAULT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.valoracion ALTER COLUMN id SET DEFAULT nextval('public.valoracion_id_seq'::regclass);


--
-- Data for Name: chat; Type: TABLE DATA; Schema: public; Owner: mouad
--

COPY public.chat (id, contenido, created_at, fecha_hora, updated_at, visto, emisor_id, receptor_id) FROM stdin;
1	Hola maouad!	2025-05-25 23:42:15.005597	2025-05-25 23:42:14.98766	2025-05-26 07:54:19.169168	t	1	3
2	fsdfs	2025-05-26 07:54:27.566086	2025-05-26 07:54:27.565254	2025-05-26 07:54:34.98071	t	3	1
3	sdf	2025-05-26 07:54:34.12816	2025-05-26 07:54:34.127198	2025-05-26 07:54:39.121795	t	1	3
4	kjgk	2025-05-26 07:54:44.640725	2025-05-26 07:54:44.639499	2025-05-26 07:54:44.979202	t	3	1
5	Hola Mouad	2025-05-26 16:27:01.056161	2025-05-26 16:27:01.012608	2025-05-26 16:27:01.056231	f	1	3
\.


--
-- Data for Name: comentario; Type: TABLE DATA; Schema: public; Owner: mouad
--

COPY public.comentario (id, contenido, created_at, fecha, img, updated_at, usuario_id, post_id) FROM stdin;
12	ghuj	2025-05-06 20:10:07.925556	2025-05-06 20:10:07.924445	\N	2025-05-06 20:10:07.925606	3	3
14	fewcds	2025-05-07 01:02:01.995256	2025-05-07 01:02:01.994728	\N	2025-05-07 01:02:01.995292	3	1
15	scdc d	2025-05-07 01:02:06.566373	2025-05-07 01:02:06.565352	\N	2025-05-07 01:02:06.566408	3	2
16	d vscds 🐵	2025-05-07 01:04:51.401794	2025-05-07 01:04:51.401343	\N	2025-05-07 01:04:51.401809	3	5
17	🦮	2025-05-07 01:04:57.266647	2025-05-07 01:04:57.265939	\N	2025-05-07 01:04:57.266672	3	5
18	kharya	2025-05-07 13:15:29.228775	2025-05-07 13:15:29.213007	\N	2025-05-07 13:15:29.228819	3	1
25	Me meo con estos pollitos! 	2025-05-12 20:36:33.196969	2025-05-12 20:36:33.185095	\N	2025-05-12 20:36:33.197017	1	39
26	que frio!!!	2025-05-12 20:37:20.008868	2025-05-12 20:37:20.008304	\N	2025-05-12 20:37:20.008896	1	40
37	asdS	2025-05-23 04:04:47.319267	2025-05-23 04:04:47.318283	\N	2025-05-23 04:04:47.319305	1	28
43	hhs	2025-05-23 12:41:59.925288	2025-05-23 12:41:59.885648	\N	2025-05-23 12:41:59.925379	1	28
44	jkjhjk	2025-05-23 17:37:38.01085	2025-05-23 17:37:37.966342	\N	2025-05-23 17:37:38.010932	1	40
45	hj	2025-05-24 18:17:43.277391	2025-05-24 18:17:43.249224	\N	2025-05-24 18:17:43.277496	1	23
46	jjj	2025-05-24 18:18:21.335365	2025-05-24 18:18:21.334493	\N	2025-05-24 18:18:21.3354	1	5
47	kkk	2025-05-24 18:18:27.518413	2025-05-24 18:18:27.517481	\N	2025-05-24 18:18:27.518473	1	3
48	hkjhj	2025-05-26 07:51:26.484932	2025-05-26 07:51:26.364623	\N	2025-05-26 07:51:26.48513	1	23
\.


--
-- Data for Name: evento; Type: TABLE DATA; Schema: public; Owner: mouad
--

COPY public.evento (id, descripcion, fecha, nombre, ubicacion) FROM stdin;
1	salchichas unidos 	2025-05-23	Salshcias reunion	mataro
\.


--
-- Data for Name: grupo; Type: TABLE DATA; Schema: public; Owner: mouad
--

COPY public.grupo (id, nombre, descripcion) FROM stdin;
4	Perros callejeros	zshxdrjytkujyrthd
5	paseos	para pasar
\.


--
-- Data for Name: mascota; Type: TABLE DATA; Schema: public; Owner: mouad
--

COPY public.mascota (id, genero, nombre, especie, usuario_id, foto, fecha_nacimiento) FROM stdin;
1	Macho	Lucas	Pato	1	mascotas/2025/05/b94c5456-8fbf-4ac5-a7f9-c2b2326d60e8.jpg	2025-05-01
11	Macho	Gato Dev	Gato 	24	mascotas/2025/05/3f2127a3-3e5f-4eec-b1c9-df419036b843.jpeg	2021-04-14
12	Macho	Perro Programador	Perro	25	mascotas/2025/05/38ab47b2-308c-46f2-9a32-b041deb050fe.jpg	2018-07-24
13	Macho	Gato IT	Gato	26	mascotas/2025/05/c3bd9746-b72c-4b17-888d-5a8a21a8ba68.jpeg	2017-01-12
\.


--
-- Data for Name: notificaciones; Type: TABLE DATA; Schema: public; Owner: mouad
--

COPY public.notificaciones (id, fecha) FROM stdin;
\.


--
-- Data for Name: perfil; Type: TABLE DATA; Schema: public; Owner: mouad
--

COPY public.perfil (id, usuario_id, descripcion, fecha_nacimiento, img) FROM stdin;
16	8	Soy un amante de los perros	1990-01-01	posts/2025/05/71b0d7ca-6823-4bda-a1f7-053ec4481bea.jpg
21	1	Hola, estoy creando esto!!!	1997-03-10	posts/2025/05/1742db55-967b-462d-b584-6da3f028de40.jpg
22	24	¡Hola, soy Yago Morales!	2018-09-17	posts/2025/05/f131dcd5-9086-4a40-b16f-1ca602b69714.jpeg
23	25	¡Hola, soy Fernando Porrino!	2024-01-25	posts/2025/05/1aa9de49-fc13-4b03-8b82-a9f72d49a106.jpg
24	26	¡Hola, soy Luis Elía!	2022-09-21	posts/2025/05/d9186b2b-9b3a-44e0-a016-d5922d0d3d3e.jpg
3	3	Hola, me llamo Mouad10	2003-07-13	posts/2025/05/9dd45694-5d58-4401-b90d-bad7cf428076.jpeg
\.


--
-- Data for Name: post; Type: TABLE DATA; Schema: public; Owner: mouad
--

COPY public.post (id, grupo_id, creador_id, contenido, fecha, img, created_at, updated_at) FROM stdin;
3	\N	1	El retrato de POPI.	2025-04-10 20:38:08.37809	https://images.pexels.com/photos/1851164/pexels-photo-1851164.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1	2025-04-10 20:38:08.427828	2025-04-11 16:15:45.33574
1	\N	1	Este es un nuevo post	2025-04-01 00:00:00	https://images.pexels.com/photos/45170/kittens-cat-cat-puppy-rush-45170.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1	\N	2025-04-11 16:16:22.485728
2	\N	1	Hoy tuvimos una caminata con los perritos del refugio (PRUEBA)	2025-04-10 18:31:33.409983	https://images.pexels.com/photos/33287/dog-viszla-close.jpg?auto=compress&cs=tinysrgb&w=600	2025-04-10 18:31:33.437484	2025-04-11 16:17:47.107813
5	\N	3	Paseando a mi gato.	2025-04-11 16:26:38.988433	https://scontent-mad2-1.xx.fbcdn.net/v/t39.30808-6/464555325_8558598987522595_4024770004962422813_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=127cfc&_nc_ohc=urpUzOvrTIIQ7kNvwH9w2MW&_nc_oc=AdmWqo6UZymyM9_lrUY5ZC_UBW0z5dmzG3By-pdiAYoOO6-mOwudBYOetMVrSX8iH18&_nc_zt=23&_nc_ht=scontent-mad2-1.xx&_nc_gid=9oynF_w7A0JJmPoZUjwVoA&oh=00_AfHFtKyEPZTKOC9NHzDCPWmKGjeSiJhBwNfXQPXZnVH9vw&oe=67FEF35E	2025-04-11 16:26:38.989125	2025-04-11 16:26:38.989153
8	\N	1	Lo que vimos hoy en el parque.	2025-04-11 17:48:29.542252	https://images.pexels.com/photos/460775/pexels-photo-460775.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1	2025-04-11 17:48:29.561819	2025-04-11 17:48:29.561958
9	\N	3	Nuevo miembro en la familia.2	2025-04-11 19:16:32.224763	https://images.pexels.com/photos/59523/pexels-photo-59523.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1	2025-04-11 19:16:32.259106	2025-04-11 19:16:32.259172
13	\N	1	dcsfc 	2025-04-14 16:21:53.657208	https://media.istockphoto.com/id/1395878741/es/foto/formaci%C3%B3n-de-pastor-belga.jpg?s=612x612&w=0&k=20&c=GMdWQWLSe47_Uvq93wyjzbMQXpmQ6r_lncnbeFoMrgs=	2025-04-14 16:21:53.658181	2025-04-14 16:21:53.65822
14	\N	1	Con mi gato	2025-04-14 16:29:45.415518	https://imagenes.elpais.com/resizer/v2/L6HBHYIV233RQH75ZJWWTFSIVM.jpg?auth=4bd07f210948e2141605fcd598cecb02199a9af44625e01362801e3efb0e72d9&width=1960&height=1470&smart=true	2025-04-14 16:29:45.41597	2025-04-14 16:29:45.415988
15	\N	1	fvgbhnij	2025-04-14 16:40:05.054857	https://i.gifer.com/origin/2e/2e24e08b6d57c9db57c3ed51091aa5f3_w200.webp	2025-04-14 16:40:05.055357	2025-04-14 16:40:05.055378
16	\N	3	efvbrgtyngvefcds	2025-04-15 00:43:30.294659	\N	2025-04-15 00:43:30.341787	2025-04-15 00:43:30.341857
17	\N	3	vfevwed	2025-04-15 00:43:57.056941	\N	2025-04-15 00:43:57.057785	2025-04-15 00:43:57.05781
18	\N	3	Portero	2025-04-15 00:44:29.644549	https://i.gifer.com/origin/4f/4f5d1807ba2d22d9de3f1abb925cab9c_w200.gif	2025-04-15 00:44:29.64534	2025-04-15 00:44:29.645362
19	\N	3	🐕‍🦺🦮	2025-04-15 00:59:30.424484	\N	2025-04-15 00:59:30.425157	2025-04-15 00:59:30.425202
20	\N	3	🦜	2025-04-15 23:59:18.146844	\N	2025-04-15 23:59:18.182323	2025-04-15 23:59:18.182409
21	\N	3	🦮	2025-04-29 19:03:16.623519	\N	2025-04-29 19:03:16.624475	2025-04-29 19:03:16.624585
22	\N	3	Buenos dias! Hemos ido a dar una vuelta y nos hemos quedado sin luz!! suerte que tenemos una muy buena linterna :)	2025-04-29 19:06:49.77979	https://i0.wp.com/blog.cuidamimascota.com/wp-content/uploads/2020/01/1344e-jack-waiting-1.gif?resize=203%2C360&ssl=1	2025-04-29 19:06:49.780692	2025-04-29 19:06:49.780727
23	\N	3	Un pato es para toda la vida!	2025-04-29 19:13:38.738668	https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Anas_platyrhynchos_qtl1.jpg/1024px-Anas_platyrhynchos_qtl1.jpg	2025-04-29 19:13:38.778723	2025-04-29 19:13:38.778816
25	\N	3	dd	2025-05-05 19:39:40.433032	vv	2025-05-05 19:39:40.433686	2025-05-05 19:39:40.433708
26	\N	3	fg b d	2025-05-06 17:01:53.7608	\N	2025-05-06 17:01:53.769845	2025-05-06 17:01:53.769886
27	\N	3	Perros	2025-05-06 19:11:35.575171	https://www.infobae.com/resizer/v2/ZJ7J3APDKNGTXPTWS6H2EKCUKU.jpg?auth=2f59d41907d2ab0799312d22027d6cb00f2ea7d59fb2037756d6f4b6d6b833cf&smart=true&width=1200&height=675&quality=85	2025-05-06 19:11:35.624767	2025-05-06 19:11:35.62481
28	\N	3	zbi 	2025-05-06 19:27:43.337957	\N	2025-05-06 19:27:43.338408	2025-05-06 19:27:43.338421
38	\N	1	Pollitos 20210	2025-05-12 20:33:33.07929	posts/2025/05/92e50f3e-e073-41ad-b523-02b11d7d0f58.jpg	2025-05-12 20:33:33.080066	2025-05-12 20:33:33.080104
39	\N	1	Pollitos y mas pollitos. 	2025-05-12 20:36:19.1877	posts/2025/05/29d8e036-2f52-4ee9-bb6e-1eb5025c1749.jpg	2025-05-12 20:36:19.188576	2025-05-12 20:36:19.188628
40	\N	1	Perros	2025-05-12 20:37:06.963642	posts/2025/05/18eb8919-6046-4638-9bc0-8e9312c68dcc.jpg	2025-05-12 20:37:06.964397	2025-05-12 20:37:06.964437
\.


--
-- Data for Name: seguido; Type: TABLE DATA; Schema: public; Owner: mouad
--

COPY public.seguido (id, usuario_que_es_seguido_id, usuario_que_sigue_id) FROM stdin;
1	3	1
2	1	3
3	3	8
4	1	8
5	24	26
6	25	26
7	26	25
8	24	25
9	25	24
10	26	24
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: mouad
--

COPY public.usuario (id, nombre, email, password, apellido) FROM stdin;
8	Prueba	Prueba@ejemplo.com	$2a$10$qEdrO.My/Z0FSNUm/QC4NODH6wWU.PtPwtwPtskoLdiYGHtE3xfdC	Prueba
3	Mouad	msedjari@elpuig.xeill.net	$2a$10$qEdrO.My/Z0FSNUm/QC4NODH6wWU.PtPwtwPtskoLdiYGHtE3xfdC	Sedjari
1	Fernando	fdiaz1997@gmail.com	$2a$10$7EUeb7fwyxeMNkKpoDqES.DAR.WJKeHaIP3xoXjnFuq6Vu05PtJKO	Diaz
20	Lucas	ddd@gmail.com	$2a$10$Symuhc2/3qcD0pm16XFjN.aiybNee0SWusRJxfy1UEBB.NVzX3pf6	sada
24	Yago	yago.morales@elpuig.xeill.net	$2a$10$IingKenPvV298Obpv8TXY.jvAqI34JfSf6V7Ngwq4vSCSG3m66J96	Morales
25	Fernando	porrino.fernando@elpuig.xeill.net	$2a$10$ExuP.7XV8PFPDxa1cc6BkOs5wejfuf5j2RooOIpFOBP926NI8oeZO	Porrino
26	 Luis	luis@elpuig.xeill.net	$2a$10$eEmnOv2l6HCWwBGQUqw3Ye5EymZMy7djA2KHpMrGzQ9.L5PJfPPUC	Elía
\.


--
-- Data for Name: usuario_evento; Type: TABLE DATA; Schema: public; Owner: mouad
--

COPY public.usuario_evento (id, rol, evento_id, usuario_id) FROM stdin;
1	CREADOR	1	1
\.


--
-- Data for Name: usuario_grupo; Type: TABLE DATA; Schema: public; Owner: mouad
--

COPY public.usuario_grupo (id, grupo_id, usuario_id, rol) FROM stdin;
14	4	3	Admin
15	4	3	Miembro
16	4	3	Miembro
17	4	3	Miembro
18	4	3	Miembro
19	4	3	Miembro
20	4	3	Miembro
21	4	3	Miembro
22	4	3	Miembro
23	4	3	Miembro
24	4	3	Miembro
25	4	3	Miembro
26	4	3	Miembro
27	4	3	Miembro
28	4	3	Miembro
29	4	3	Miembro
30	4	3	Miembro
31	4	3	Miembro
32	4	3	Miembro
33	4	3	Miembro
34	4	3	Miembro
35	4	3	Miembro
36	4	3	Miembro
37	4	3	Miembro
38	4	3	Miembro
39	4	3	Miembro
40	4	3	Miembro
41	4	3	Miembro
42	4	3	Miembro
43	4	3	Miembro
44	4	3	Miembro
45	4	3	Miembro
46	4	3	Miembro
47	4	3	Miembro
48	5	1	Admin
49	4	1	Miembro
\.


--
-- Data for Name: usuario_post; Type: TABLE DATA; Schema: public; Owner: mouad
--

COPY public.usuario_post (id, fecha, post_id, usuario_id) FROM stdin;
6	2025-05-23 03:59:08.169678	23	1
7	2025-05-23 03:59:10.695009	22	1
\.


--
-- Data for Name: valoracion; Type: TABLE DATA; Schema: public; Owner: fernando
--

COPY public.valoracion (id, autor_id, receptor_id, puntuacion, contenido, fecha, created_at, updated_at) FROM stdin;
9	3	1	5	Muy buen cuidador, me mandaba fotos de mi mascota cada dia!	2025-05-26 22:11:16.924	2025-05-27 00:11:17.002232	2025-05-27 00:11:17.002308
10	1	3	5	Le deje a mi perra y cada vez que lo ve lo quiere saludar. Un trato excelente.	2025-05-26 22:12:11.686	2025-05-27 00:12:11.761797	2025-05-27 00:12:11.761825
\.


--
-- Name: Usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mouad
--

SELECT pg_catalog.setval('public."Usuario_id_seq"', 26, true);


--
-- Name: chat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mouad
--

SELECT pg_catalog.setval('public.chat_id_seq', 5, true);


--
-- Name: comentario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mouad
--

SELECT pg_catalog.setval('public.comentario_id_seq', 48, true);


--
-- Name: evento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mouad
--

SELECT pg_catalog.setval('public.evento_id_seq', 1, true);


--
-- Name: grupo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mouad
--

SELECT pg_catalog.setval('public.grupo_id_seq', 6, true);


--
-- Name: mascota_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mouad
--

SELECT pg_catalog.setval('public.mascota_id_seq', 13, true);


--
-- Name: notificaciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mouad
--

SELECT pg_catalog.setval('public.notificaciones_id_seq', 1, false);


--
-- Name: perfil_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mouad
--

SELECT pg_catalog.setval('public.perfil_id_seq', 24, true);


--
-- Name: post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mouad
--

SELECT pg_catalog.setval('public.post_id_seq', 54, true);


--
-- Name: seguido_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mouad
--

SELECT pg_catalog.setval('public.seguido_id_seq', 10, true);


--
-- Name: usuario_evento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mouad
--

SELECT pg_catalog.setval('public.usuario_evento_id_seq', 1, true);


--
-- Name: usuario_grupo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mouad
--

SELECT pg_catalog.setval('public.usuario_grupo_id_seq', 50, true);


--
-- Name: usuario_post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mouad
--

SELECT pg_catalog.setval('public.usuario_post_id_seq', 10, true);


--
-- Name: valoracion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fernando
--

SELECT pg_catalog.setval('public.valoracion_id_seq', 10, true);


--
-- Name: usuario Usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT "Usuario_pkey" PRIMARY KEY (id);


--
-- Name: chat chat_pkey; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT chat_pkey PRIMARY KEY (id);


--
-- Name: comentario comentario_pkey; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.comentario
    ADD CONSTRAINT comentario_pkey PRIMARY KEY (id);


--
-- Name: evento evento_pkey; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.evento
    ADD CONSTRAINT evento_pkey PRIMARY KEY (id);


--
-- Name: grupo grupo_pkey; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.grupo
    ADD CONSTRAINT grupo_pkey PRIMARY KEY (id);


--
-- Name: mascota mascota_pkey; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.mascota
    ADD CONSTRAINT mascota_pkey PRIMARY KEY (id);


--
-- Name: notificaciones notificaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.notificaciones
    ADD CONSTRAINT notificaciones_pkey PRIMARY KEY (id);


--
-- Name: perfil perfil_pkey; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.perfil
    ADD CONSTRAINT perfil_pkey PRIMARY KEY (id);


--
-- Name: post post_pkey; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_pkey PRIMARY KEY (id);


--
-- Name: seguido seguido_pkey; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.seguido
    ADD CONSTRAINT seguido_pkey PRIMARY KEY (id);


--
-- Name: perfil uk_perfil_usuario_id; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.perfil
    ADD CONSTRAINT uk_perfil_usuario_id UNIQUE (usuario_id);


--
-- Name: perfil ukqimyhrxv3rmjmv7cs5fi1ek85; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.perfil
    ADD CONSTRAINT ukqimyhrxv3rmjmv7cs5fi1ek85 UNIQUE (usuario_id);


--
-- Name: usuario_evento usuario_evento_pkey; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.usuario_evento
    ADD CONSTRAINT usuario_evento_pkey PRIMARY KEY (id);


--
-- Name: usuario_grupo usuario_grupo_pkey; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.usuario_grupo
    ADD CONSTRAINT usuario_grupo_pkey PRIMARY KEY (id);


--
-- Name: usuario_post usuario_post_pkey; Type: CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.usuario_post
    ADD CONSTRAINT usuario_post_pkey PRIMARY KEY (id);


--
-- Name: valoracion valoracion_pkey; Type: CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.valoracion
    ADD CONSTRAINT valoracion_pkey PRIMARY KEY (id);


--
-- Name: usuario_evento fk8x76e33rsidpp4bishwdd04lh; Type: FK CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.usuario_evento
    ADD CONSTRAINT fk8x76e33rsidpp4bishwdd04lh FOREIGN KEY (evento_id) REFERENCES public.evento(id);


--
-- Name: comentario fk_comentario_post; Type: FK CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.comentario
    ADD CONSTRAINT fk_comentario_post FOREIGN KEY (post_id) REFERENCES public.post(id) ON DELETE CASCADE;


--
-- Name: post fk_creador; Type: FK CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT fk_creador FOREIGN KEY (creador_id) REFERENCES public.usuario(id) ON DELETE CASCADE;


--
-- Name: post fk_grupo; Type: FK CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT fk_grupo FOREIGN KEY (grupo_id) REFERENCES public.grupo(id) ON DELETE CASCADE;


--
-- Name: usuario_grupo fk_grupo; Type: FK CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.usuario_grupo
    ADD CONSTRAINT fk_grupo FOREIGN KEY (grupo_id) REFERENCES public.grupo(id) ON DELETE CASCADE;


--
-- Name: perfil fk_perfil_usuario; Type: FK CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.perfil
    ADD CONSTRAINT fk_perfil_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(id) ON DELETE CASCADE;


--
-- Name: usuario_grupo fk_usuario; Type: FK CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.usuario_grupo
    ADD CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(id) ON DELETE CASCADE;


--
-- Name: chat fkcnfx4tcx0mjdwqfolg0ajypu3; Type: FK CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fkcnfx4tcx0mjdwqfolg0ajypu3 FOREIGN KEY (emisor_id) REFERENCES public.usuario(id);


--
-- Name: usuario_evento fkgsiny8oonbc82c44qsnd29nm8; Type: FK CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.usuario_evento
    ADD CONSTRAINT fkgsiny8oonbc82c44qsnd29nm8 FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- Name: comentario fkixspmid2pb85o8ypsd20jakxg; Type: FK CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.comentario
    ADD CONSTRAINT fkixspmid2pb85o8ypsd20jakxg FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- Name: usuario_post fknv8vbueu7ie3u1as6gords0i9; Type: FK CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.usuario_post
    ADD CONSTRAINT fknv8vbueu7ie3u1as6gords0i9 FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- Name: chat fkomcfygas78eyx4j5hyxv1kf2u; Type: FK CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fkomcfygas78eyx4j5hyxv1kf2u FOREIGN KEY (receptor_id) REFERENCES public.usuario(id);


--
-- Name: usuario_post fksb2ejtvfhs09ds7ho10nya4xr; Type: FK CONSTRAINT; Schema: public; Owner: mouad
--

ALTER TABLE ONLY public.usuario_post
    ADD CONSTRAINT fksb2ejtvfhs09ds7ho10nya4xr FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: valoracion valoracion_autor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.valoracion
    ADD CONSTRAINT valoracion_autor_id_fkey FOREIGN KEY (autor_id) REFERENCES public.usuario(id);


--
-- Name: valoracion valoracion_receptor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: fernando
--

ALTER TABLE ONLY public.valoracion
    ADD CONSTRAINT valoracion_receptor_id_fkey FOREIGN KEY (receptor_id) REFERENCES public.usuario(id);


--
-- PostgreSQL database dump complete
--

